title: Jimmy Space
description: It is a blog record my tech ecc experience in my life!
theme: just-the-docs
plugins:
  - jekyll-default-layout
url: https://blog.deepbytes.cn/

permalink: pretty

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

favicon_ico: "/assets/images/blog-logo.png"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable heading anchors
heading_anchors: true

# For copy button on code
enable_copy_code_button: true
